% -------------------------------------------------------------------
%  Generated by MATLAB on 1-May-2024 15:45:37
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
saveVarsMat = load('Signals.mat');

SW_1 = mpt.Signal;
SW_1.CoderInfo.StorageClass = 'Custom';
SW_1.CoderInfo.Identifier = '';
SW_1.CoderInfo.Alignment = -1;
SW_1.CoderInfo.CustomStorageClass = 'Global';
SW_1.CoderInfo.CustomAttributes.MemorySection = 'Default';
SW_1.CoderInfo.CustomAttributes.HeaderFile = '';
SW_1.CoderInfo.CustomAttributes.DefinitionFile = '';
SW_1.CoderInfo.CustomAttributes.Owner = '';
SW_1.CoderInfo.CustomAttributes.PersistenceLevel = 1;
SW_1.Description = '';
SW_1.DataType = 'boolean';
SW_1.Min = [];
SW_1.Max = [];
SW_1.DocUnits = '';
SW_1.Dimensions = -1;
SW_1.DimensionsMode = 'auto';
SW_1.Complexity = 'auto';
SW_1.SampleTime = -1;
SW_1.InitialValue = '';

SW_2 = mpt.Signal;
SW_2.CoderInfo.StorageClass = 'Custom';
SW_2.CoderInfo.Identifier = '';
SW_2.CoderInfo.Alignment = -1;
SW_2.CoderInfo.CustomStorageClass = 'Global';
SW_2.CoderInfo.CustomAttributes.MemorySection = 'Default';
SW_2.CoderInfo.CustomAttributes.HeaderFile = '';
SW_2.CoderInfo.CustomAttributes.DefinitionFile = '';
SW_2.CoderInfo.CustomAttributes.Owner = '';
SW_2.CoderInfo.CustomAttributes.PersistenceLevel = 1;
SW_2.Description = '';
SW_2.DataType = 'boolean';
SW_2.Min = [];
SW_2.Max = [];
SW_2.DocUnits = '';
SW_2.Dimensions = -1;
SW_2.DimensionsMode = 'auto';
SW_2.Complexity = 'auto';
SW_2.SampleTime = -1;
SW_2.InitialValue = '';

SW_3 = mpt.Signal;
SW_3.CoderInfo.StorageClass = 'Custom';
SW_3.CoderInfo.Identifier = '';
SW_3.CoderInfo.Alignment = -1;
SW_3.CoderInfo.CustomStorageClass = 'Global';
SW_3.CoderInfo.CustomAttributes.MemorySection = 'Default';
SW_3.CoderInfo.CustomAttributes.HeaderFile = '';
SW_3.CoderInfo.CustomAttributes.DefinitionFile = '';
SW_3.CoderInfo.CustomAttributes.Owner = '';
SW_3.CoderInfo.CustomAttributes.PersistenceLevel = 1;
SW_3.Description = '';
SW_3.DataType = 'boolean';
SW_3.Min = [];
SW_3.Max = [];
SW_3.DocUnits = '';
SW_3.Dimensions = -1;
SW_3.DimensionsMode = 'auto';
SW_3.Complexity = 'auto';
SW_3.SampleTime = -1;
SW_3.InitialValue = '';

SW_4 = mpt.Signal;
SW_4.CoderInfo.StorageClass = 'Custom';
SW_4.CoderInfo.Identifier = '';
SW_4.CoderInfo.Alignment = -1;
SW_4.CoderInfo.CustomStorageClass = 'Global';
SW_4.CoderInfo.CustomAttributes.MemorySection = 'Default';
SW_4.CoderInfo.CustomAttributes.HeaderFile = '';
SW_4.CoderInfo.CustomAttributes.DefinitionFile = '';
SW_4.CoderInfo.CustomAttributes.Owner = '';
SW_4.CoderInfo.CustomAttributes.PersistenceLevel = 1;
SW_4.Description = '';
SW_4.DataType = 'boolean';
SW_4.Min = [];
SW_4.Max = [];
SW_4.DocUnits = '';
SW_4.Dimensions = -1;
SW_4.DimensionsMode = 'auto';
SW_4.Complexity = 'auto';
SW_4.SampleTime = -1;
SW_4.InitialValue = '';

Voltage_cell_1 = mpt.Signal;
Voltage_cell_1.CoderInfo.StorageClass = 'Custom';
Voltage_cell_1.CoderInfo.Identifier = '';
Voltage_cell_1.CoderInfo.Alignment = -1;
Voltage_cell_1.CoderInfo.CustomStorageClass = 'Global';
Voltage_cell_1.CoderInfo.CustomAttributes.MemorySection = 'Default';
Voltage_cell_1.CoderInfo.CustomAttributes.HeaderFile = '';
Voltage_cell_1.CoderInfo.CustomAttributes.DefinitionFile = '';
Voltage_cell_1.CoderInfo.CustomAttributes.Owner = '';
Voltage_cell_1.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Voltage_cell_1.Description = '';
Voltage_cell_1.DataType = 'single';
Voltage_cell_1.Min = [];
Voltage_cell_1.Max = [];
Voltage_cell_1.DocUnits = '';
Voltage_cell_1.Dimensions = -1;
Voltage_cell_1.DimensionsMode = 'auto';
Voltage_cell_1.Complexity = 'auto';
Voltage_cell_1.SampleTime = -1;
Voltage_cell_1.InitialValue = '';

Voltage_cell_2 = mpt.Signal;
Voltage_cell_2.CoderInfo.StorageClass = 'Custom';
Voltage_cell_2.CoderInfo.Identifier = '';
Voltage_cell_2.CoderInfo.Alignment = -1;
Voltage_cell_2.CoderInfo.CustomStorageClass = 'Global';
Voltage_cell_2.CoderInfo.CustomAttributes.MemorySection = 'Default';
Voltage_cell_2.CoderInfo.CustomAttributes.HeaderFile = '';
Voltage_cell_2.CoderInfo.CustomAttributes.DefinitionFile = '';
Voltage_cell_2.CoderInfo.CustomAttributes.Owner = '';
Voltage_cell_2.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Voltage_cell_2.Description = '';
Voltage_cell_2.DataType = 'single';
Voltage_cell_2.Min = [];
Voltage_cell_2.Max = [];
Voltage_cell_2.DocUnits = '';
Voltage_cell_2.Dimensions = -1;
Voltage_cell_2.DimensionsMode = 'auto';
Voltage_cell_2.Complexity = 'auto';
Voltage_cell_2.SampleTime = -1;
Voltage_cell_2.InitialValue = '';

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

clear saveVarsMat;
