% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Apr-2024 20:25:44
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
saveVarsMat = load('Signals_file.mat');

Cell1_Sw = mpt.Signal;
Cell1_Sw.CoderInfo.StorageClass = 'Custom';
Cell1_Sw.CoderInfo.Identifier = '';
Cell1_Sw.CoderInfo.Alignment = -1;
Cell1_Sw.CoderInfo.CustomStorageClass = 'Global';
Cell1_Sw.CoderInfo.CustomAttributes.MemorySection = 'Default';
Cell1_Sw.CoderInfo.CustomAttributes.HeaderFile = '';
Cell1_Sw.CoderInfo.CustomAttributes.DefinitionFile = '';
Cell1_Sw.CoderInfo.CustomAttributes.Owner = '';
Cell1_Sw.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Cell1_Sw.Description = '';
Cell1_Sw.DataType = 'auto';
Cell1_Sw.Min = [];
Cell1_Sw.Max = [];
Cell1_Sw.DocUnits = '';
Cell1_Sw.Dimensions = -1;
Cell1_Sw.DimensionsMode = 'auto';
Cell1_Sw.Complexity = 'auto';
Cell1_Sw.SampleTime = -1;
Cell1_Sw.InitialValue = '';

Cell2_Sw = mpt.Signal;
Cell2_Sw.CoderInfo.StorageClass = 'Custom';
Cell2_Sw.CoderInfo.Identifier = '';
Cell2_Sw.CoderInfo.Alignment = -1;
Cell2_Sw.CoderInfo.CustomStorageClass = 'Global';
Cell2_Sw.CoderInfo.CustomAttributes.MemorySection = 'Default';
Cell2_Sw.CoderInfo.CustomAttributes.HeaderFile = '';
Cell2_Sw.CoderInfo.CustomAttributes.DefinitionFile = '';
Cell2_Sw.CoderInfo.CustomAttributes.Owner = '';
Cell2_Sw.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Cell2_Sw.Description = '';
Cell2_Sw.DataType = 'boolean';
Cell2_Sw.Min = [];
Cell2_Sw.Max = [];
Cell2_Sw.DocUnits = '';
Cell2_Sw.Dimensions = -1;
Cell2_Sw.DimensionsMode = 'auto';
Cell2_Sw.Complexity = 'auto';
Cell2_Sw.SampleTime = -1;
Cell2_Sw.InitialValue = '';

Cell3_Sw = mpt.Signal;
Cell3_Sw.CoderInfo.StorageClass = 'Custom';
Cell3_Sw.CoderInfo.Identifier = '';
Cell3_Sw.CoderInfo.Alignment = -1;
Cell3_Sw.CoderInfo.CustomStorageClass = 'Global';
Cell3_Sw.CoderInfo.CustomAttributes.MemorySection = 'Default';
Cell3_Sw.CoderInfo.CustomAttributes.HeaderFile = '';
Cell3_Sw.CoderInfo.CustomAttributes.DefinitionFile = '';
Cell3_Sw.CoderInfo.CustomAttributes.Owner = '';
Cell3_Sw.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Cell3_Sw.Description = '';
Cell3_Sw.DataType = 'boolean';
Cell3_Sw.Min = [];
Cell3_Sw.Max = [];
Cell3_Sw.DocUnits = '';
Cell3_Sw.Dimensions = -1;
Cell3_Sw.DimensionsMode = 'auto';
Cell3_Sw.Complexity = 'auto';
Cell3_Sw.SampleTime = -1;
Cell3_Sw.InitialValue = '';

Voltage_cell_1 = mpt.Signal;
Voltage_cell_1.CoderInfo.StorageClass = 'Custom';
Voltage_cell_1.CoderInfo.Identifier = '';
Voltage_cell_1.CoderInfo.Alignment = -1;
Voltage_cell_1.CoderInfo.CustomStorageClass = 'Global';
Voltage_cell_1.CoderInfo.CustomAttributes.MemorySection = 'Default';
Voltage_cell_1.CoderInfo.CustomAttributes.HeaderFile = '';
Voltage_cell_1.CoderInfo.CustomAttributes.DefinitionFile = '';
Voltage_cell_1.CoderInfo.CustomAttributes.Owner = '';
Voltage_cell_1.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Voltage_cell_1.Description = '';
Voltage_cell_1.DataType = 'single';
Voltage_cell_1.Min = 0;
Voltage_cell_1.Max = [];
Voltage_cell_1.DocUnits = '';
Voltage_cell_1.Dimensions = -1;
Voltage_cell_1.DimensionsMode = 'auto';
Voltage_cell_1.Complexity = 'auto';
Voltage_cell_1.SampleTime = -1;
Voltage_cell_1.InitialValue = '';

Voltage_cell_2 = mpt.Signal;
Voltage_cell_2.CoderInfo.StorageClass = 'Custom';
Voltage_cell_2.CoderInfo.Identifier = '';
Voltage_cell_2.CoderInfo.Alignment = -1;
Voltage_cell_2.CoderInfo.CustomStorageClass = 'Global';
Voltage_cell_2.CoderInfo.CustomAttributes.MemorySection = 'Default';
Voltage_cell_2.CoderInfo.CustomAttributes.HeaderFile = '';
Voltage_cell_2.CoderInfo.CustomAttributes.DefinitionFile = '';
Voltage_cell_2.CoderInfo.CustomAttributes.Owner = '';
Voltage_cell_2.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Voltage_cell_2.Description = '';
Voltage_cell_2.DataType = 'single';
Voltage_cell_2.Min = 0;
Voltage_cell_2.Max = [];
Voltage_cell_2.DocUnits = '';
Voltage_cell_2.Dimensions = -1;
Voltage_cell_2.DimensionsMode = 'auto';
Voltage_cell_2.Complexity = 'auto';
Voltage_cell_2.SampleTime = -1;
Voltage_cell_2.InitialValue = '';

Voltage_cell_3 = mpt.Signal;
Voltage_cell_3.CoderInfo.StorageClass = 'Custom';
Voltage_cell_3.CoderInfo.Identifier = '';
Voltage_cell_3.CoderInfo.Alignment = -1;
Voltage_cell_3.CoderInfo.CustomStorageClass = 'Global';
Voltage_cell_3.CoderInfo.CustomAttributes.MemorySection = 'Default';
Voltage_cell_3.CoderInfo.CustomAttributes.HeaderFile = '';
Voltage_cell_3.CoderInfo.CustomAttributes.DefinitionFile = '';
Voltage_cell_3.CoderInfo.CustomAttributes.Owner = '';
Voltage_cell_3.CoderInfo.CustomAttributes.PersistenceLevel = 1;
Voltage_cell_3.Description = '';
Voltage_cell_3.DataType = 'single';
Voltage_cell_3.Min = 0;
Voltage_cell_3.Max = [];
Voltage_cell_3.DocUnits = '';
Voltage_cell_3.Dimensions = -1;
Voltage_cell_3.DimensionsMode = 'auto';
Voltage_cell_3.Complexity = 'auto';
Voltage_cell_3.SampleTime = -1;
Voltage_cell_3.InitialValue = '';

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

clear saveVarsMat;
